### ISSUE TITLE
wrong launch level log filtering

### ISSUE THREAD

**Issue by tmax22** [reportportal/service-ui#3631] opened 2023-11-01 17:30 UTC
in the launch level log view the query made by the ui client returns empty result:
<img width="717" alt="image" src="https://github.com/reportportal/service-ui/assets/147702803/4fa2df68-7e60-4bb8-abd5-657c4f188bf2">

inspecting the browsers network devtools shows http request to `
http://localhost:8080/api/v1/clearances/log?filter.eq.launch=556&filter.gte.level=DEBUG&page.page=1&page.size=50&page.sort=logTime%2CASC&filter.gte.level=DEBUG`

this query returns empty result.

make a notice for filter `filter.eq.launch=556`. chaning this to `filter.eq.launchId=556` shows up the original result. you most probaly written `lanch` instead of `launchId` in the query from the client.

making a request with `launchId` parameters brings the correct result:
<img width="353" alt="image" src="https://github.com/reportportal/service-ui/assets/147702803/02eadd1e-cac0-4fdf-bc70-7fcc1d6577d4">

**Comment by Pink-Bumblebee** [comment] 2023-11-02 09:01
Could you please clarify what kind of version of RP you are using? Our latest version is 23.2 (5.10.1)

**Comment by tmax22** [comment] 2023-11-02 13:11
i'm using the [latest docker-compose](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml) setup which indeed uses 23.2 version. but the `service-ui` uses 5.10.0. the only service that is updated to use 5.10.1 is the [service-api](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L192) service

**Comment by tmax22** [comment] 2023-11-02 13:14
i would be happy to open PR for this fix and even for other issues i would encouter later, but your [development docker-compose file](https://github.com/reportportal/reportportal/blob/master/dev-deployment/docker-compose.yml) is outdated so it's hard to setup the development enviroment correctly

**Comment by Pink-Bumblebee** [comment] 2023-11-03 10:09
> i'm using the [latest docker-compose](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml) setup which indeed uses 23.2 version. but the `service-ui` uses 5.10.0. the only service that is updated to use 5.10.1 is the [service-api](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L192) service

Yes. It is latest release 23.2 (5.10.0) with hotfix of service-api (5.10.1)

**Comment by tmax22** [comment] 2023-11-22 18:40
Hey, I have found the bug: https://github.com/reportportal/service-ui/blob/1f0fc5f221e9ca996ef67be3895eee04d44ab508/app/src/common/urls.js#L224

`'filter.eq.launch'` should be replaced with `'filter.eq.launchId'`
now launch level filtering works as expected

**Comment by tmax22** [comment] 2023-11-22 18:45
i've actually managed to successfully migrate the entire development server to vitejs (with minimal changes to the source code and with custom vite plugins)

if you are interested I can work on extracting relevant code into a dedicated pull request(in case you guys want instant hmr reloass instead of waiting 30 seconds between saving)

**Comment by alena-babrova** [comment] 2023-11-28 07:45
Dear @tmax22,

Could you please describe on what level do you post logs? Do you post logs for Launch level or for nested levels (e.g. Suite, Step, Test)?
Because the current page (Launch log view) is designed to display only logs of Launch level.

**Comment by tmax22** [comment] 2023-12-13 15:09
it is possible that i've did not understand the 'all logs' page as intended. do you mean by `logs of Launch level`? sometimes we really want to search for a log in all the launches

**Comment by alena-babrova** [comment] 2023-12-14 07:32
Dear @tmax22,

1. There is no functionality to see all Logs of all Launches.
2. As for the "Logs View" page, it displays logs **ONLY for the current level, not including nested levels**. E.g.
   a. Launch -> "Logs View" -> displays all logs related to the Launch level
   b. Launch -> Suite -> "Logs View" -> displays all logs related to the Suite level
   c. Launch -> Suite -> Test -> "Logs View" -> displays all logs related to the Test level
   etc.

**Comment by tmax22** [comment] 2023-12-14 08:53
I'm sorry, I meant all logs for **all cases per launch**.

now I get it, we didn't realize that a specific launch case host a suite which hosts steps. in our case, each launch hosts directly steps.

this issue directly related to `2.b:  Launch -> Suite -> "Logs View" -> displays all logs related to the Suite level`.
in our case, there is no suite level. each launch contains directly the steps. if a launch contain only steps, by design, the logs view of the launch should be able to view these logs. please consider adding it. (in our case we thought this is a bug so we just changed the query to fit our case)

by the way, you have a great system! the best out there in the category.

**Comment by alena-babrova** [comment] 2023-12-18 07:42
Dear @tmax22,

Yes, as I mentioned above, "Logs View" page displays only logs of the current level but not including the child levels. This is by design. Anyway, we will discuss the possible improvement here as you suggested.

And thank you for your feedback - we appreciate it very much and will do our best to improve our product and documentation as well.

I am closing the ticket as resolved (works as designed).

**Closed by alena-babrova** 2023-12-18 07:42 UTC
