### ISSUE TITLE
Firefox - Auto Analysis Icons are larger then normal - v5.5.0

### ISSUE THREAD

**Issue by jigneshmm** [reportportal/service-ui#2793] opened 2021-08-09 15:55 UTC
Steps to Reproduce:
1. Login to ReportPortal
2. Navigate to Failed Test Case that is Auto Analyzed
3. Verify UI on Test Step Screen and Test Log screen
See below screenshots
Test Step Screen
![image](https://user-images.githubusercontent.com/63611247/128736121-9c2f5883-35b2-47a2-add9-f53254f35883.png)

Test Log Screen:
![image](https://user-images.githubusercontent.com/63611247/128736195-306f1372-8b90-454f-b70a-282e6979e7f1.png)
![image](https://user-images.githubusercontent.com/63611247/128736258-0816d296-3e17-434e-80f1-df2b1f8ee496.png)

**Comment by VolhaKarenko** [comment] 2021-08-10 09:50
@jigneshmm could you please specify Firefox version you are using? The issue is not reproducible on Firefox 90.0.2

**Comment by jigneshmm** [comment] 2021-08-10 12:18
> @jigneshmm could you please specify Firefox version you are using? The issue is not reproducible on Firefox 90.0.2

90.0.2
![image](https://user-images.githubusercontent.com/63611247/128865413-b89989ea-3ce3-46bc-a9b5-772daa2e08d5.png)

**Comment by VolhaKarenko** [comment] 2021-08-10 13:50
Reproducible on local instance, bug is added to backlog

**Comment by AmsterGet** [comment] 2021-09-03 09:30
Fixed in 5.5.1.

**Closed by AmsterGet** 2021-09-03 09:30 UTC
Labels: bug, 5.5.1
