### ISSUE TITLE
[v5.0.0-RC-3] UI doesn't open/show video and log attachments

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [reportportal/service-ui#2243] opened 2019-12-03 13:07 UTC
Some attachments with a content type like **log** or **video** don't show correctly in the UI.
I assume that some `Content-Type` HTTP headers are not being processed correctly by UI
`Content-Type: text/x-log`
`Content-Type: video/mp4`
but 
`Content-Type: image/png` - works as expected

For example, 
1. Video file
![Screenshot 2019-12-03 at 2 49 26 PM](https://user-images.githubusercontent.com/55390366/70052885-ee1ba900-15dc-11ea-88a0-f08c69525509.png)
It doesn't open in attachment UI, but can be downloaded via curl and open by some video player:
```
$ curl 'https://reportportal.example.com/api/v1/data/mobile/NC8zMzYvOGEvYzYvYjkvY2EtMTQ2My00NDcxLWIxYWYtYjM0OWZiOTFkNGI2L2JpbmFyeV9wYXJ0LnBuZw' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Accept: application/json, text/plain, */*' -H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzUzNzczNjUsInVzZXJfbmFtZSI6InN1cGVyYWRtaW4iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOSVNUUkFUT1IiXSwianRpIjoiYTExMDdkOTAtN2U5OC00ZTU4LTk5ODgtNmViYjgwNGU4OWVhIiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.W0UcwgpBl9RR2Hk7HYDXp6-BY9nc7w3it4gK8JIoTNE' \
--compressed > attachment.mp4
```

2. Log text file
![Screenshot 2019-12-03 at 2 24 54 PM](https://user-images.githubusercontent.com/55390366/70053263-b2351380-15dd-11ea-8398-4356ab1c4bcb.png)
![Screenshot 2019-12-03 at 2 25 02 PM](https://user-images.githubusercontent.com/55390366/70053264-b2cdaa00-15dd-11ea-98ba-8149338fda07.png)

**Comment by sandeepnagra** [comment] 2019-12-06 15:41
I am experiencing same issue with v5.0.0-RC-3. When I click on the thumbnail it downloads the .mov file.

![image](https://user-images.githubusercontent.com/9598669/70335250-f4946580-1814-11ea-9f15-c8252ece661d.png)

**Comment by evjlobanova** [comment] 2020-03-31 17:08
The duplicate of #2352 ttps://github.com/reportportal/reportportal/issues/117

**Closed** 2020-03-31 17:09 UTC
